#!/usr/bin/env php
<?php

/**
 * File console
 *
 * @author Edward Pfremmer <epfremme@nerdery.com>
 */

use PHPWeekly\Issue36\Application;

require_once __DIR__ . '/../vendor/autoload.php';

$application = new Application();
$application->run();
